weights: ./runs/train/exp88/weights/best.pt
cfg: ./models/hub/yolov5s6.yaml
data: ./data/mogo_vehicle_7.yaml
hyp: data/hyps/hyp.scratch.yaml
epochs: 100
batch_size: 128
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: 0,1,2,3
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 32
project: runs/train
entity: null
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
local_rank: -1
freeze: 0
save_dir: runs/train/exp109
